version: '3'

services:
  lottery_node:
    image: node:lts
    container_name: lottery_node
    volumes:
      - ./:/app
    working_dir: "/app"
    ports:
      - "127.0.0.1:8001:8001"
      - "3001:3001"
    tty: true
    networks:
      - default

networks: 
  default: